Сделано ДЗ по ООП-3 Наследование
Lelena1/oop3 pull request #1
Opened 2022-11-24 23:55 UTC by Lelena1

Проверьте, пожалуйста, ДЗ

2022-11-25 07:54 UTC, OlgaLugacheva requested changes

2022-11-25 07:54 UTC, OlgaLugacheva commented on Train.java
> +        if (departureStation != null && !departureStation.isEmpty() && !departureStation.isBlank()) {
валидацию строки можно вынести в отдельный метод и класс утилит

2022-11-25 07:54 UTC, OlgaLugacheva commented on zoo/Amphibians.java
> +    public void eat() {
нужно было написать какую-то реализацию

2022-11-25 07:54 UTC, OlgaLugacheva commented on zoo/Amphibians.java
> +    public void go() {
и сюда

2022-11-26 14:15 UTC, Lelena1 commented on Train.java
> +        if (departureStation != null && !departureStation.isEmpty() && !departureStation.isBlank()) {
исправила

2022-11-26 14:15 UTC, Lelena1 commented on zoo/Amphibians.java
> +    public void eat() {
исправила

2022-11-26 14:15 UTC, Lelena1 commented on zoo/Amphibians.java
> +    public void go() {
исправила

2022-11-27 17:33 UTC, merged